MvcApiPracticaChollos/Models/Chollo.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MvcApiPracticaChollos.Models
{
    public class Chollo
    {
        public int IdChollo { get; set; }

        public string Titulo { get; set; }

        public string Link { get; set; }

        public string Descripcion { get; set; }

        public DateTime Fecha { get; set; }

    }
}

MvcApiPracticaChollos/Models/ErrorViewModel.cs
namespace MvcApiPracticaChollos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcApiPracticaChollos/Controllers/CholloController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiPracticaChollos.Models;
using MvcApiPracticaChollos.Services;

namespace MvcApiPracticaChollos.Controllers
{
    public class CholloController : Controller
    {
        private ServiceChollos service;
        public CholloController(ServiceChollos service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Chollo> chollos = await this.service.GetChollosAsync();
            return View(chollos);
        }

        public async Task<IActionResult> Details(int id)
        {
            Chollo chollo = await this.service.FindChollo(id);
            return View(chollo);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Chollo chollo)
        {
            await this.service.InsertChollo(chollo.IdChollo, chollo.Titulo, chollo.Link, chollo.Descripcion, chollo.Fecha);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int id)
        {
           Chollo chollo =  await this.service.FindChollo(id);
            return View(chollo);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Chollo chollo)
        {
           
            await this.service.UpdateChollo(chollo.IdChollo, chollo.Titulo, chollo.Link, chollo.Descripcion, chollo.Fecha);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.service.DeleteChollo(id);
            return RedirectToAction("Index");
        }
        
    }
}

MvcApiPracticaChollos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiPracticaChollos.Models;
using System.Diagnostics;

namespace MvcApiPracticaChollos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcApiPracticaChollos/Views/Chollo/Create.cshtml
@model MvcApiPracticaChollos.Models.Chollo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Chollo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdChollo" class="control-label"></label>
                <input asp-for="IdChollo" class="form-control" />
                <span asp-validation-for="IdChollo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApiPracticaChollos/Views/Chollo/Details.cshtml
@model MvcApiPracticaChollos.Models.Chollo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Chollo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdChollo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdChollo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcApiPracticaChollos/Views/Chollo/Edit.cshtml
@model MvcApiPracticaChollos.Models.Chollo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Chollo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="IdChollo" class="control-label"></label>
                <input asp-for="IdChollo" class="form-control" />
                <span asp-validation-for="IdChollo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApiPracticaChollos/Views/Chollo/Index.cshtml
@model IEnumerable<MvcApiPracticaChollos.Models.Chollo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdChollo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Link)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdChollo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Link)
                </td>
                <td>
                    @Html.Raw(@item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.IdChollo  }) |
                    @Html.ActionLink("Details", "Details", new {  id=item.IdChollo }) |
                    @Html.ActionLink("Delete", "Delete", new {  id=item.IdChollo })
                </td>
            </tr>
        }
    </tbody>
</table>

MvcApiPracticaChollos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcApiPracticaChollos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApiPracticaChollos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcApiPracticaChollos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApiPracticaChollos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chollo" asp-action="Index">Chollos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcApiPracticaChollos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>